# Generated by Django 6.0.1 on 2026-02-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='content',
            field=models.CharField(max_length=300),
        ),
    ]
